function(stm32f4_get_chip_info CHIP)
    string(TOUPPER ${CHIP} CHIP_UPPER)
    string(LENGTH "${CHIP_UPPER}" CHIP_LEN)

    if(CHIP_LEN LESS 11)
        message(FATAL_ERROR "Invalid STM32 chip name: ${CHIP} (expected e.g. STM32F407VG)")
    endif()

    string(SUBSTRING "${CHIP_UPPER}" 5 4 FAMILY)
    string(SUBSTRING "${CHIP_UPPER}" 10 1 FLASH_LETTER)

    if(FLASH_LETTER STREQUAL "8")
        set(FLASH "64K")
    elseif(FLASH_LETTER STREQUAL "B")
        set(FLASH "128K")
    elseif(FLASH_LETTER STREQUAL "C")
        set(FLASH "256K")
    elseif(FLASH_LETTER STREQUAL "D")
        set(FLASH "384K")
    elseif(FLASH_LETTER STREQUAL "E")
        set(FLASH "512K")
    elseif(FLASH_LETTER STREQUAL "G")
        set(FLASH "1024K")
    elseif(FLASH_LETTER STREQUAL "H")
        set(FLASH "1536K")
    elseif(FLASH_LETTER STREQUAL "I")
        set(FLASH "2048K")
    else()
        message(FATAL_ERROR "Unknown flash size letter '${FLASH_LETTER}' in chip ${CHIP}")
    endif()

    if(FAMILY MATCHES "F401")
        if(FLASH_LETTER MATCHES "[8BC]")
            set(RAM "64K")
            set(DEFINE "STM32F401xC")
        else()
            set(RAM "96K")
            set(DEFINE "STM32F401xE")
        endif()
        set(CCM "0K")
        set(VECTORS "vectors_stm32f401xx.c")

    elseif(FAMILY MATCHES "F405")
        set(RAM "128K")
        set(CCM "64K")
        set(DEFINE "STM32F405xx")
        set(VECTORS "vectors_stm32f405xx.c")

    elseif(FAMILY MATCHES "F407")
        set(RAM "128K")
        set(CCM "64K")
        set(DEFINE "STM32F407xx")
        set(VECTORS "vectors_stm32f407xx.c")

    elseif(FAMILY MATCHES "F411")
        set(RAM "128K")
        set(CCM "0K")
        set(DEFINE "STM32F411xE")
        set(VECTORS "vectors_stm32f411xx.c")

    elseif(FAMILY MATCHES "F412")
        set(RAM "256K")
        set(CCM "0K")
        set(DEFINE "STM32F412Vx")
        set(VECTORS "vectors_stm32f412xx.c")

    elseif(FAMILY MATCHES "F429")
        set(RAM "192K")
        set(CCM "64K")
        set(DEFINE "STM32F429xx")
        set(VECTORS "vectors_stm32f429xx.c")

    elseif(FAMILY MATCHES "F439")
        set(RAM "192K")
        set(CCM "64K")
        set(DEFINE "STM32F439xx")
        set(VECTORS "vectors_stm32f429xx.c")

    elseif(FAMILY MATCHES "F446")
        set(RAM "128K")
        set(CCM "0K")
        set(DEFINE "STM32F446xx")
        set(VECTORS "vectors_stm32f446xx.c")

    else()
        message(FATAL_ERROR "Unsupported STM32F4 family: ${FAMILY} (chip: ${CHIP})\n"
            "Supported: F401, F405, F407, F411, F412, F429, F439, F446")
    endif()

    set(STM32_FLASH_SIZE ${FLASH} PARENT_SCOPE)
    set(STM32_RAM_SIZE ${RAM} PARENT_SCOPE)
    set(STM32_CCM_SIZE ${CCM} PARENT_SCOPE)
    set(STM32_DEFINE ${DEFINE} PARENT_SCOPE)
    set(STM32_VECTORS_FILE ${VECTORS} PARENT_SCOPE)
    set(STM32_ARCH_FLAGS "-mcpu=cortex-m4;-mthumb;-mfloat-abi=soft" PARENT_SCOPE)

    message(STATUS "STM32 chip: ${CHIP}")
    message(STATUS "  Flash: ${FLASH}, RAM: ${RAM}, CCM: ${CCM}")
    message(STATUS "  Define: ${DEFINE}, Vectors: ${VECTORS}")
endfunction()
